trigger: none

resources:
  containers:
  - container: agent_container21
    image: microsoft/dotnet:2.1-sdk
  - container: agent_container22
    image: microsoft/dotnet:2.2-sdk
  - container: sqlserver
    image: microsoft/mssql-server-linux
    options: -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=StrongPassw0rd"
    ports:
      - 1433:1433
  - container: redislatest
    image: redis:alpine
    ports:
      - 6379:6379
  - container: redis4
    image: redis:4.0.13-alpine
    ports:
      - 6379:6379
 
pool: penguins
#  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    redislatest:
      redisService: redisLatest
      containerImage: agent_container21
    redis4:
      redisService: redis4
      containerImage: agent_container21
    redissdk22latest:
      redisService: redisLatest
      containerImage: agent_container22
 
container:  $[ variables['containerImage'] ]

services:
  sqlserver: sqlserver
  redis: $[ variables['redisService'] ]
 
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/FunctionalTests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/FunctionalTests.csproj'
